spring:
  application:
    name: vector-tracing
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false
    sender:
      type: web
    enabled: false
  sleuth:
    sampler:
      rate: 100  #抽样采集率(%)

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
    enabled: true

server:
  port: 9600