#模拟feign负载均衡，服务提供者实例2
replication: vector-bizservice-2

spring:
  application:
    name: vector-bizservice

server:
  port: 9102

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
