#模拟feign负载均衡，服务提供者实例1
replication: vector-bizservice-1

spring:
  application:
    name: vector-bizservice

server:
  port: 9101

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
